language: php
php:
  - '7.0'
  
addons:
    code_climate:
        repo_token: ed55d15b5fe0950b535003f0aaece251df35b058a0521617fa6fc2c4b49aad8e

install:
  - composer self-update
  - make install

script: make lint test

after_script:
  - vendor/bin/test-reporter